### ISSUE TITLE
Random location method.

### ISSUE THREAD

**Issue by RE4ERKA** [DailyStruggle/RTP#22]
Call a method that will find a random location with your plugin.

Can be used to create a random location for air drops for example, I would like to have an optimized way to do this, which is what your plugin does and I see that you are currently working on a v2 version of the plugin.

Sorry if there already is, I couldn't find info about it in the wiki.

**Comment by DailyStruggle** [comment]
it's not in the wiki, but it's easily found in the code.

https://github.com/DailyStruggle/RTP/blob/V1/src/main/java/leafcraft/rtp/tools/Cache.java#L184
v2 is currently working by region name alone
