### ISSUE TITLE
/rtp not working for non-ops

### ISSUE THREAD

**Issue by panterathehacker** [DailyStruggle/RTP#27]
Hi there -- I get this console error when a non-op uses the /rtp command:
https://pastebin.com/iJcS0vf6

The plugin THINKS they have teleported (the cooldown starts, and if they try again it says they are already teleporting).

Using most recent version of the plugin and of paper.

They have the rtp.use and rtp.free permissions.

**Comment by panterathehacker** [comment]
Fixed issue. /rtp reload did not reload the config files (despite the messaging saying it did). A server restart reloaded them.

**Comment by DailyStruggle** [comment]
latest version is unstable

I haven't seen this issue in a while so I assumed it was fixed.

**Comment by DailyStruggle** [comment]
op vs non-op will not affect whether or not the sqlite interaction happens. If they weren't teleporting, it's probably a separate issue.

**Comment by DailyStruggle** [comment]
attempting to teleport during or shortly after a reload seems to trigger some problems, primarily getting stuck in a teleport command

**Comment by DailyStruggle** [comment]
patched in latest commit, players should no longer be able to rtp during the reload process
