### ISSUE TITLE
vault pricing doesnt work in 1.12.2

### ISSUE THREAD

**Issue by professorparabellum** [DailyStruggle/RTP#30]
i set a region (for the end world) to cost $5000 but the problem is that when a player runs /rtp region:end the money isnt debited from their balance.

**Comment by professorparabellum** [comment]
im not really sure but a reason this may be happening is because I have "price: 0.0" set in economy.yml, because I want rtp in the overworld to be free. Just not for the end or nether

**Comment by DailyStruggle** [comment]
I don't think I properly implemented per-region prices yet because other features took priority

**Comment by DailyStruggle** [comment]
should be fixed in latest commit

**Comment by professorparabellum** [comment]
ok great thank you so much!
