### ISSUE TITLE
[PROBABLY A BUG] Discord links in spigot description have expired

### ISSUE THREAD

**Issue by hucario** [DailyStruggle/RTP#35]
**Describe the bug**
The discord links (sidebar under "Ask Questions/Get Support" and in the FAQ) in the Spigot resource's description have expired.
Both lead to [this link](https://discord.com/invite/SdQrEfNZXm), which when clicked shows it has expired.

**Context**
N/A

**To Reproduce**
Go to [the RTP resource page](https://www.spigotmc.org/resources/rtp.94812/) and click either Discord link.

**Expected behavior**
You should be prompted to enter a Discord server of some kind.
If this is intended behavior (i.e. you have shut down the server / don't want people entering it), please remove the links.

**Screenshots**
![20230801_13h22m59s_grim](https://github.com/DailyStruggle/RTP/assets/50851047/55a5d858-5c6c-40c9-af35-9eeb381e37bc)
![20230801_13h23m51s_grim](https://github.com/DailyStruggle/RTP/assets/50851047/dad06253-430e-4b0d-8db8-ff1c5fbbf3b0)
![20230801_13h26m19s_grim](https://github.com/DailyStruggle/RTP/assets/50851047/896ed45f-ec49-4e77-b076-4d42e64ed4cb)

**Comment by DailyStruggle** [comment]
intended outcome is a limited number of uses of the link, to limit spam risks. It will be updated today
