### ISSUE TITLE
[FEATURE] RTP range presets

### ISSUE THREAD

**Issue by BlamBlam1256** [DailyStruggle/RTP#36]
**Is your feature request related to a problem? Please describe.**
Not really

**Describe the solution you'd like**
A way to add multiple presets with different rtp range's.
I'm hosting a server that has this plugin in it, but I want it to use a ranking system where the more you rank up the further you can rtp from spawn.
I am using luckperms for the permissions so being able to select for example "rtp.preset.2k" or "rtp.preset.5k" would be extremly helpfull.

thx
(sorry for any bad english, not my main language xp)

**Comment by DailyStruggle** [comment]
Is there anything preventing you from making multiple regions and using the permission override system?

**Comment by BlamBlam1256** [comment]
thanks for the quick response xD
i'll look into that a bit, i'll let you know if it worked

thx

**Comment by BlamBlam1256** [comment]
> Is there anything preventing you from making multiple regions and using the permission override system?

so I have added the regions but i'm not really understanding the override system..
do I change the override name from default to like 5k? 
then how do I add it so a player automatically is added to that region instead of having to do /rtp region:5k

if you could help me out a bit that would extremly apprectiated 😅

**Comment by BlamBlam1256** [comment]
small edit, the regions did now appear in the luckperms editor. 
I have added a 5k radius and a 10k.
do I have to set the requirepermission to true for the 5 and 10k and then simply add the rtp.regions.5k and 10k to the player rank I want? will that automatically send them to the default if they don't have the required rank?

edit:
I have added the permissions to the rank I want but it doesn't seem to do much so maybe I did something wrong in the config..

this is what I changed in the configs:

(everyone has the perm rtp.region.default and rtp.use) 
for the default I have:
#check rtp.regions.[region] node on command
requirePermission: false
#if no perms, try this one
override: default

(the rank that unlocks this has the rtp.region.5k )
for 5k:
#check rtp.regions.[region] node on command
requirePermission: true
#if no perms, try this one
override: default

(the rank that has this has the rtp.region.10k )
and for 10k:
#check rtp.regions.[region] node on command
requirePermission: true
#if no perms, try this one
override: 5k


(I'll have to sleep now because I have to get up early but will be here again tomorrow.. I hope you can help me out 😅 thx )

**Comment by DailyStruggle** [comment]
> I have added the permissions to the rank

what permissions did you add?

also what commands are you running?

**Comment by BlamBlam1256** [comment]
> > I have added the permissions to the rank
> 
> what permissions did you add?
> 
> also what commands are you running?

sorry for the late reply (work)
so I got it running with the permissions to only allow players to use a certain radius. 
if I would now try /rtp region:10k
it won't work because I have no perms, but If I wanted to do /rtp region:default or 5k it would.

but how would I make it so using the regular /rtp looks at what region it can teleport instead of having to choose the region yourself?

the regions I made:
![image](https://github.com/DailyStruggle/RTP/assets/123770500/767c49b3-eb6a-4f87-8dc8-18c7554a14b6)

default config to keep you from tping if you have no perms:
![image](https://github.com/DailyStruggle/RTP/assets/123770500/e495e641-c8a1-4b8e-a355-feba79fa83dd)

5k config sends you to default if you have no perms: 
![image](https://github.com/DailyStruggle/RTP/assets/123770500/d7196c54-74e5-4dac-8da7-40f058ecaae2)

10k config sends you to 5k if you have no perms: 
![image](https://github.com/DailyStruggle/RTP/assets/123770500/16efae46-4a6f-4478-9ceb-fc5119cb51d4)

when adding these perms to my player:
![image](https://github.com/DailyStruggle/RTP/assets/123770500/2fe9dcfb-7288-4cff-beea-f2385711dd0f)

only the 5k region shows up here and works using that:
![image](https://github.com/DailyStruggle/RTP/assets/123770500/2a419751-e111-43d1-a826-1580b7222f06)

but it still only teleports within the default region when using the normal /rtp command

is there any config that can change this?

**Comment by DailyStruggle** [comment]
> but how would I make it so using the regular /rtp looks at what region it can teleport instead of having to choose the region yourself?

make a plugin

or maybe start the loop with default.yml instead of 10k

RTP should handle multiple overrides as it is now

This plugin is a platform to work with and is not an end-all solution to every use case. For this type of "it works, but I want it to work my way" problem, you should consider simply editing the open-source code or using command aliases
