### ISSUE TITLE
Support ChunkyBorder

### ISSUE THREAD

**Issue by TomLewis** [DailyStruggle/RTP#4]
Please support the border plugin ChunkyBorder, I installed the plugin and it automatically generated a ton of chunks outside my ChunkBorder, but inside my vanilla WorldBorder, The Vanilla worldborder is only set so it does not display on Dynmap, but as RTP generated a metric ton of chunks outside my world border its messed up the Dynmap now too!
https://www.spigotmc.org/resources/chunkyborder.84278/

I cant see a getting started guide on the wiki or the spigot page, but im assuming I need to setup a "region" for each world to limit how far it sends people out? 

Just be nice if it supported ChunkyBorder to automatically pickup the world border.

**Comment by DailyStruggle** [comment]
unable to reproduce initial selections outside worldborder, but it should be impossible now

**Comment by DailyStruggle** [comment]
I could not add chunkyBorder to main plugin due to a lack of maven repo (would cause build errors on github and complicate user compilation), 

so I rewrote worldborder checking to make it more arbitrary and added an example addon for injecting a ChunkyBorder worldborder checker into RTP
