### ISSUE TITLE
[BUG] Config maxY/minY get ignored.

### ISSUE THREAD

**Issue by lolo45654** [DailyStruggle/RTP#41]
**Describe the bug**
The vertical adjustor minY/maxY always use hardcoded values. I used a custom world generation of a desert where the terrain is at about y 260, which is higher than the hardcoded values.

**Context**
Java version: Java 21
Server build: Purpur 2151
Server version: 1.20.4
Player version: 1.20.4
Plugins:  Chunky, CommandAPI, F3NPerm, FastAsyncWorldEdit, FasterCrystals, GrimAC, LPC, LuckPerms, packetdelay, PersonalKits, RTP, spark, Terra, ViaBackwards, ViaVersion, voicechat

I compiled the plugin myself to find out what happened, changes made due to compile errors:
- deleted src/test (javafx not found)
- removed javadoc plugin in pom.xml
these changes should not affect the function of the plugin.

**To Reproduce**
1. Setup a server with [Terra](https://modrinth.com/plugin/terra)
2. Add [desert.zip](https://github.com/DailyStruggle/RTP/files/14585781/desert.zip) to plugins/Terra/packs
3. Modify bukkit.yml:
```yaml
worlds:
  world:
    generator: Terra:DUNE_DESERT
```
4. Start the server with no changes made to the plugin / config and rtp (doesn't work)
5. Start the server with maxY changed to 320 and rtp (still doesn't work)
6. Start the server with the suggested changes below and maxY changed to 320, rtp (works fine)

**Expected behavior**
Config should be respected

**Screenshots**
\-

**Cause**
[Region.java#L958](https://github.com/DailyStruggle/RTP/blob/67a6a0fd685f63b5b245c50f55c8f5fd12f90558/src/main/java/io/github/dailystruggle/rtp/common/selection/region/Region.java#L958)

The map validY is being modified before the data changes, and is being used after the data changes. Moving the map changes to after data change, fixed it for me.

**Comment by DailyStruggle** [comment]
Given long term testing showing the settings working and the overall lack of utilization of "validY" since splitting the values, I find this to be an unlikely bug and solution, the assumptions here may be premature.

I'll run tests later to confirm the issue.
