### ISSUE TITLE
Consider compiling the plugin with a lower version of java

### ISSUE THREAD

**Issue by iMrDJAi** [DailyStruggle/RTP#9]
```
[09:26:12 ERROR]: Could not load 'plugins\RTP-1.3.23.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: leafcraft/rtp/RTP has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 56.0
```

**Comment by DailyStruggle** [comment]
the newer java versions are more efficient and it seems I can run every version of spigot back to 1.8 using the latest java version.

Is there a particular reason to use older java versions?

**Comment by iMrDJAi** [comment]
@DailyStruggle Paper 1.13.2 refused to work with the most recent version of java. Am I missing something?

**Comment by iMrDJAi** [comment]
I'm getting `Unsupported Java detected (61.0). Only up to Java 12 is supported.` when running spigot 1.13.2 on java 17.

**Comment by DailyStruggle** [comment]
the first problem is that several softdepends are using newer java versions and the plugin won't compile without removing a bunch of plugin checks.

the second problem is that I used a several methods introduced in newer java versions and it's tedious to revert.

**Comment by DailyStruggle** [comment]
I realize now I compiled my server without the version check

**Comment by iMrDJAi** [comment]
@DailyStruggle You mean this check? https://www.spigotmc.org/wiki/buildtools/#dev

Not sure how to remove it from Paper as there are no official buildtools for it.

**Comment by DailyStruggle** [comment]
don't edit server source code for a plugin setup process. It's safer to recompile the plugin.

**Comment by DailyStruggle** [comment]
I'm not doing this on v1 because I can't as easily decouple the softdependencies from the plugin

**Comment by iMrDJAi** [comment]
@DailyStruggle Alright! No problem. Just focus on v2, I'm really excited about it!

**Comment by DailyStruggle** [comment]
working compilation in java 8 on the V2 branch, supporting a better form of reflection for location checks so that softdependencies can be external to the main plugin.
